name: Auto Merge to Release Branches

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Merge release/dev branch into main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "asunarto@corelogic.com"
        git config --global user.name "Andrew Sunarto"
        git config --global pull.ff only
        git clone "https://${{ secrets.USER }}:${{ secrets.TOKEN }}@github.com/adsunarto/Kafka_Ops_POC.git"
        git fetch
        cd Kafka_Ops_POC
        git checkout release/dev
        git pull
        git push
        git checkout main
        git pull
        git push
        git merge release/dev

    # - name: Rebase release/prd branch
    #   env:
    #     GH_PAT: ${{ secrets.GH_PAT }}
    #   run: |
    #     git remote update
    #     git fetch
    #     git checkout --track origin/release/prd
    #     git pull origin release/dev
    #     git rebase main
    #     git push --force origin release/prd
