name: Auto Merge to Release Branches

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge main -> release/dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: release/dev
          github_token: ${{ secrets.TOKEN }}
