name: Auto Merge to Release Branches

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Merge to nonproduction branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git checkout release/dev
        git pull
        git merge main
        git push origin release/dev

    - name: Merge to production branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git checkout release/prd
        git pull
        git merge main
        git push origin release/prd

