name: Auto Merge to Release Branches

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Rebase release/dev branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git checkout origin/release/dev
        git pull
        git rebase master
        git push --force origin release/dev

    - name: Rebase release/prd branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git checkout origin/release/prd
        git pull
        git rebase master
        git push --force origin release/prd